apiVersion: 0.3.0
environments:
  default:
    destination:
      namespace: kubeflow
      server: https://35.239.82.68
    k8sVersion: v1.11.7
    path: default
kind: ksonnet.io/app
libraries:
  kubeflow/tf-serving:
    name: tf-serving
    registry: kubeflow
    version: 797bcb7407a589bacc35b9624120f51f36a83468
name: demo_ks_app
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/v0.4.1/kubeflow
version: 0.0.1
