#This container contains your model and any helper scripts specific to your model.
FROM tensorflow/tensorflow:1.13.1

ADD ctp_model.py /opt/ctp_model.py

ADD input/santander-ctp/train.csv /opt/train.csv

RUN chmod +x /opt/ctp_model.py

RUN pip install pandas

ENTRYPOINT ["/usr/bin/python"]
CMD ["/opt/ctp_model.py"]
